src/nl/strohalm/cyclos/entities/ads/imports/ImportedAdCategory.java
/*
    This file is part of Cyclos (www.cyclos.org).
    A project of the Social Trade Organisation (www.socialtrade.org).

    Cyclos is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    Cyclos is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Cyclos; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

 */
package nl.strohalm.cyclos.entities.ads.imports;

import nl.strohalm.cyclos.entities.Entity;
import nl.strohalm.cyclos.entities.Relationship;
import nl.strohalm.cyclos.entities.ads.AdCategory;

/**
 * An imported ad category, which was still not processed
 * 
 * @author luis
 */
public class ImportedAdCategory extends Entity {

    public static enum Relationships implements Relationship {
        AD_IMPORT("adImport"), IMPORTED_PARENT("importedParent"), EXISTING_PARENT("existingParent");

        private final String name;

        private Relationships(final String name) {
            this.name = name;
        }

        public String getName() {
            return name;
        }
    }

    private static final long  serialVersionUID = 3881658859416912467L;

    private AdImport           adImport;
    private String             name;
    private ImportedAdCategory importedParent;
    private AdCategory         existingParent;

    public AdImport getAdImport() {
        return adImport;
    }

    public AdCategory getExistingParent() {
        return existingParent;
    }

    public String getFullName() {
        if (existingParent == null && importedParent == null) {
            return name;
        } else if (existingParent != null) {
            return existingParent.getFullName() + ": " + name;
        } else {
            return importedParent.getFullName() + ": " + name;
        }
    }

    public ImportedAdCategory getImportedParent() {
        return importedParent;
    }

    public String getName() {
        return name;
    }

    public void setAdImport(final AdImport adImport) {
        this.adImport = adImport;
    }

    public void setExistingParent(final AdCategory existingParent) {
        this.existingParent = existingParent;
    }

    public void setImportedParent(final ImportedAdCategory importedParent) {
        this.importedParent = importedParent;
    }

    public void setName(final String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return getId() + " - " + name;
    }

}

src/nl/strohalm/cyclos/controls/ads/imports/ImportAdsAction.java
/*
    This file is part of Cyclos (www.cyclos.org).
    A project of the Social Trade Organisation (www.socialtrade.org).

    Cyclos is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    Cyclos is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Cyclos; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

 */
package nl.strohalm.cyclos.controls.ads.imports;

import java.util.List;

import javax.servlet.http.HttpServletRequest;

import nl.strohalm.cyclos.annotations.Inject;
import nl.strohalm.cyclos.controls.ActionContext;
import nl.strohalm.cyclos.controls.BaseFormAction;
import nl.strohalm.cyclos.entities.accounts.Currency;
import nl.strohalm.cyclos.entities.ads.imports.AdImport;
import nl.strohalm.cyclos.services.accounts.CurrencyService;
import nl.strohalm.cyclos.services.ads.AdImportService;
import nl.strohalm.cyclos.utils.ActionHelper;
import nl.strohalm.cyclos.utils.binding.BeanBinder;
import nl.strohalm.cyclos.utils.binding.DataBinder;
import nl.strohalm.cyclos.utils.binding.PropertyBinder;
import nl.strohalm.cyclos.utils.csv.UnknownColumnException;
import nl.strohalm.cyclos.utils.validation.RequiredError;
import nl.strohalm.cyclos.utils.validation.ValidationException;

import org.apache.struts.action.ActionForward;
import org.apache.struts.upload.FormFile;

/**
 * Action used to import advertisements
 * 
 * @author luis
 */
public class ImportAdsAction extends BaseFormAction {
    private AdImportService      adImportService;
    private CurrencyService      currencyService;
    private DataBinder<AdImport> dataBinder;

    public DataBinder<AdImport> getDataBinder() {
        if (dataBinder == null) {
            final BeanBinder<AdImport> binder = BeanBinder.instance(AdImport.class);
            binder.registerBinder("currency", PropertyBinder.instance(Currency.class, "currency"));
            dataBinder = binder;
        }
        return dataBinder;
    }

    @Inject
    public void setAdImportService(final AdImportService adImportService) {
        this.adImportService = adImportService;
    }

    @Inject
    public void setCurrencyService(final CurrencyService currencyService) {
        this.currencyService = currencyService;
    }

    @Override
    protected ActionForward handleSubmit(final ActionContext context) throws Exception {
        final ImportAdsForm form = context.getForm();
        final FormFile upload = form.getUpload();
        if (upload == null || upload.getFileSize() == 0) {
            throw new ValidationException("upload", "adImport.file", new RequiredError());
        }
        AdImport adImport = getDataBinder().readFromString(form.getImport());
        try {
            adImport = adImportService.importAds(adImport, upload.getInputStream());
            return ActionHelper.redirectWithParam(context.getRequest(), context.getSuccessForward(), "importId", adImport.getId());
        } catch (final UnknownColumnException e) {
            return context.sendError("general.error.csv.unknownColumn", e.getColumn());
        } finally {
            upload.destroy();
        }
    }

    @Override
    protected void prepareForm(final ActionContext context) throws Exception {
        final HttpServletRequest request = context.getRequest();
        final List<Currency> currencies = currencyService.listAll();
        if (currencies.size() == 1) {
            request.setAttribute("singleCurrency", currencies.get(0));
        }
        request.setAttribute("currencies", currencies);
    }

    @Override
    protected void validateForm(final ActionContext context) {
        final ImportAdsForm form = context.getForm();
        final AdImport adImport = getDataBinder().readFromString(form.getImport());
        adImportService.validate(adImport);
    }

}

src/nl/strohalm/cyclos/controls/ads/imports/ImportedAdCategoriesAction.java
/*
    This file is part of Cyclos (www.cyclos.org).
    A project of the Social Trade Organisation (www.socialtrade.org).

    Cyclos is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    Cyclos is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Cyclos; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

 */
package nl.strohalm.cyclos.controls.ads.imports;

import javax.servlet.http.HttpServletRequest;

import nl.strohalm.cyclos.annotations.Inject;
import nl.strohalm.cyclos.controls.ActionContext;
import nl.strohalm.cyclos.controls.BaseAction;
import nl.strohalm.cyclos.entities.ads.imports.AdImport;
import nl.strohalm.cyclos.services.ads.AdImportService;
import nl.strohalm.cyclos.utils.EntityHelper;

import org.apache.struts.action.ActionForward;

/**
 * Action used to show the new categories
 * @author luis
 */
public class ImportedAdCategoriesAction extends BaseAction {

    private AdImportService adImportService;

    @Inject
    public void setAdImportService(final AdImportService adImportService) {
        this.adImportService = adImportService;
    }

    @Override
    protected ActionForward executeAction(final ActionContext context) throws Exception {
        final ImportedAdCategoriesForm form = context.getForm();
        final AdImport adImport = EntityHelper.reference(AdImport.class, form.getImportId());
        final HttpServletRequest request = context.getRequest();
        request.setAttribute("categories", adImportService.getNewCategories(adImport));
        return context.getInputForward();
    }

}

src/nl/strohalm/cyclos/controls/ads/imports/ImportedAdsDetailsAction.java
/*
    This file is part of Cyclos (www.cyclos.org).
    A project of the Social Trade Organisation (www.socialtrade.org).

    Cyclos is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    Cyclos is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Cyclos; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

 */
package nl.strohalm.cyclos.controls.ads.imports;

import java.util.List;

import javax.servlet.http.HttpServletRequest;

import nl.strohalm.cyclos.annotations.Inject;
import nl.strohalm.cyclos.controls.ActionContext;
import nl.strohalm.cyclos.controls.BaseQueryAction;
import nl.strohalm.cyclos.entities.ads.imports.AdImport;
import nl.strohalm.cyclos.entities.ads.imports.ImportedAd;
import nl.strohalm.cyclos.entities.ads.imports.ImportedAdQuery;
import nl.strohalm.cyclos.services.ads.AdImportService;
import nl.strohalm.cyclos.utils.binding.BeanBinder;
import nl.strohalm.cyclos.utils.binding.DataBinder;
import nl.strohalm.cyclos.utils.binding.DataBinderHelper;
import nl.strohalm.cyclos.utils.binding.PropertyBinder;
import nl.strohalm.cyclos.utils.query.QueryParameters;
import nl.strohalm.cyclos.utils.validation.ValidationException;

/**
 * Action used to show details for imported ads
 * @author luis
 */
public class ImportedAdsDetailsAction extends BaseQueryAction {

    private AdImportService             adImportService;
    private DataBinder<ImportedAdQuery> dataBinder;

    public DataBinder<ImportedAdQuery> getDataBinder() {
        if (dataBinder == null) {
            final BeanBinder<ImportedAdQuery> binder = BeanBinder.instance(ImportedAdQuery.class);
            binder.registerBinder("adImport", PropertyBinder.instance(AdImport.class, "adImport"));
            binder.registerBinder("status", PropertyBinder.instance(ImportedAdQuery.Status.class, "status"));
            binder.registerBinder("lineNumber", PropertyBinder.instance(Integer.class, "lineNumber"));
            binder.registerBinder("pageParameters", DataBinderHelper.pageBinder());
            return binder;
        }
        return dataBinder;
    }

    @Inject
    public void setAdImportService(final AdImportService adImportService) {
        this.adImportService = adImportService;
    }

    @Override
    protected void executeQuery(final ActionContext context, final QueryParameters queryParameters) {
        final HttpServletRequest request = context.getRequest();
        final ImportedAdQuery query = (ImportedAdQuery) queryParameters;
        final List<ImportedAd> ads = adImportService.searchImportedAds(query);
        request.setAttribute("importedAds", ads);
    }

    @Override
    protected QueryParameters prepareForm(final ActionContext context) {
        final HttpServletRequest request = context.getRequest();
        final ImportedAdsDetailsForm form = context.getForm();
        final ImportedAdQuery query = getDataBinder().readFromString(form.getQuery());
        final AdImport adImport = adImportService.load(query.getAdImport().getId(), AdImport.Relationships.CURRENCY);
        if (adImport == null || query.getStatus() == null) {
            throw new ValidationException();
        }
        query.setAdImport(adImport);
        request.setAttribute("lowercaseStatus", query.getStatus().name().toLowerCase());
        return query;
    }

    @Override
    protected boolean willExecuteQuery(final ActionContext context, final QueryParameters queryParameters) throws Exception {
        return true;
    }
}

src/nl/strohalm/cyclos/controls/ads/imports/ImportedAdsSummaryAction.java
/*
    This file is part of Cyclos (www.cyclos.org).
    A project of the Social Trade Organisation (www.socialtrade.org).

    Cyclos is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    Cyclos is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Cyclos; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

 */
package nl.strohalm.cyclos.controls.ads.imports;

import java.util.List;

import javax.servlet.http.HttpServletRequest;

import nl.strohalm.cyclos.annotations.Inject;
import nl.strohalm.cyclos.controls.ActionContext;
import nl.strohalm.cyclos.controls.BaseFormAction;
import nl.strohalm.cyclos.entities.accounts.Currency;
import nl.strohalm.cyclos.entities.ads.imports.AdImport;
import nl.strohalm.cyclos.services.accounts.CurrencyService;
import nl.strohalm.cyclos.services.ads.AdImportService;
import nl.strohalm.cyclos.utils.validation.ValidationException;

/**
 * Action used to view the import summary and to confirm the import
 * 
 * @author luis
 */
public class ImportedAdsSummaryAction extends BaseFormAction {

    private AdImportService adImportService;
    private CurrencyService currencyService;

    @Inject
    public void setAdImportService(final AdImportService adImportService) {
        this.adImportService = adImportService;
    }

    @Inject
    public void setCurrencyService(final CurrencyService currencyService) {
        this.currencyService = currencyService;
    }

    @Override
    protected void formAction(final ActionContext context) throws Exception {
        final AdImport adImport = getImport(context);
        adImportService.processImport(adImport);
        context.sendMessage("adImport.processed");
    }

    @Override
    protected void prepareForm(final ActionContext context) throws Exception {
        final AdImport adImport = getImport(context);
        final HttpServletRequest request = context.getRequest();
        request.setAttribute("adImport", adImport);
        request.setAttribute("summary", adImportService.getSummary(adImport));

        // We need to know if there's a single currency. In this case, the currency won't be shown
        final List<Currency> currencies = currencyService.listAll();
        if (currencies.size() == 1) {
            request.setAttribute("singleCurrency", currencies.get(0));
        }
    }

    private AdImport getImport(final ActionContext context) {
        final ImportedAdsSummaryForm form = context.getForm();
        try {
            return adImportService.load(form.getImportId(), AdImport.Relationships.CURRENCY);
        } catch (final Exception e) {
            throw new ValidationException();
        }
    }
}

web/pages/productsServices/imports/importAds.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://jakarta.apache.org/struts/tags/struts-bean" prefix="bean" %>
<%@ taglib uri="http://jakarta.apache.org/struts/tags/struts-html" prefix="html" %>
<%@ taglib uri="http://sslext.sf.net/tags/sslext" prefix="ssl" %>
<%@ taglib uri="http://devel.cyclos.org/tlibs/cyclos-core" prefix="cyclos" %>
<%@ taglib uri="http://www.servletsuite.com/servlets/toggletag" prefix="t" %> 

<cyclos:script src="/pages/productsServices/imports/importAds.js" />

<ssl:form method="post" action="${formAction}" enctype="multipart/form-data">
<c:if test="${not empty singleCurrency}">
	<html:hidden property="import(currency)" value="${singleCurrency.id}" />
</c:if>
<table class="defaultTableContent" cellspacing="0" cellpadding="0">
    <tr>
        <td class="tdHeaderTable"><bean:message key="adImport.title.import"/></td>
        <cyclos:help page="advertisements#import_ads"/>
    </tr>
    <tr>
        <td colspan="2" align="left" class="tdContentTableForms">
            <table class="defaultTable">
            	<c:if test="${empty singleCurrency}">
	                <tr>
	                    <td class="label" width="30%"><bean:message key="adImport.currency"/></td>
	                    <td>
	                    	<html:select styleId="currencySelect" property="import(currency)">
	                    		<c:forEach var="currency" items="${currencies}">
	                    			<html:option value="${currency.id}">${currency.name}</html:option>
	                    		</c:forEach>
	                    	</html:select>
	                    </td>
	                </tr>
                </c:if>
                <tr>
                    <td class="label" width="30%"><bean:message key="adImport.file"/></td>
                    <td><html:file property="upload" /></td>
                </tr>
                <tr>
					<td align="right" colspan="2">
	               		<input type="submit" id="submitButton" class="button" value="<bean:message key="global.submit"/>" >
					</td>
	            </tr>
             </table>
        </td>
    </tr>
</table>
</ssl:form>

web/pages/productsServices/imports/importedAdCategories.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<%@ taglib uri="http://jakarta.apache.org/struts/tags/struts-bean" prefix="bean" %>
<%@ taglib uri="http://jakarta.apache.org/struts/tags/struts-html" prefix="html" %>
<%@ taglib uri="http://sslext.sf.net/tags/sslext" prefix="ssl" %>
<%@ taglib uri="http://devel.cyclos.org/tlibs/cyclos-core" prefix="cyclos" %>
<%@ taglib uri="http://www.servletsuite.com/servlets/toggletag" prefix="t" %> 

<cyclos:script src="/pages/productsServices/imports/importedAdCategories.js" />

<ssl:form method="post" action="${formAction}">
<html:hidden property="importId"/>
<table class="defaultTableContent" cellspacing="0" cellpadding="0">
    <tr>
        <td class="tdHeaderTable"><bean:message key="adImport.title.newCategories" /></td>
        <cyclos:help page="advertisements#import_ad_categories"/> 
    </tr>
    <tr>
        <td colspan="2" align="left" class="tdContentTableLists">
			<table class="defaultTable">
				<tr>
					<td class="tdHeaderContents"><bean:message key="ad.category"/></td>
				</tr>
				<c:forEach var="category" items="${categories}">
					<tr class="<t:toggle>ClassColor1|ClassColor2</t:toggle>">
						<td>${category.fullName}</td>
					</tr>
				</c:forEach>
			</table>
		</td>
	</tr>
</table>

<table class="defaultTableContentHidden" cellpadding="0" cellspacing="0">
	<tr>
		<td><input type="button" class="button" id="backButton" value="<bean:message key="global.back"/>"></td>
	</tr>
</table>
</ssl:form>

web/pages/productsServices/imports/importedAdsDetails.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<%@ taglib uri="http://jakarta.apache.org/struts/tags/struts-bean" prefix="bean" %>
<%@ taglib uri="http://jakarta.apache.org/struts/tags/struts-html" prefix="html" %>
<%@ taglib uri="http://sslext.sf.net/tags/sslext" prefix="ssl" %>
<%@ taglib uri="http://devel.cyclos.org/tlibs/cyclos-core" prefix="cyclos" %>
<%@ taglib uri="http://www.servletsuite.com/servlets/toggletag" prefix="t" %> 

<cyclos:script src="/pages/productsServices/imports/importedAdsDetails.js" />

<ssl:form method="post" action="${formAction}">
<html:hidden property="importId"/>
<html:hidden property="status"/>
<table class="defaultTableContent" cellspacing="0" cellpadding="0">
    <tr>
        <td class="tdHeaderTable"><bean:message key="adImport.title.details.${lowercaseStatus}" /></td>
        <cyclos:help page="advertisements#imported_ad_details"/> 
    </tr>
    <tr>
        <td colspan="2" align="left" class="tdContentTableForms">
            <table class="defaultTable">            	
                <tr>
                    <td width="20%" class="label"><bean:message key="adImport.lineNumber"/></td>
                    <td><html:text property="query(lineNumber)" styleClass="number small" /></td>
					<td align="right"><input type="submit" class="button" value="<bean:message key="global.search"/>"></td>
				</tr>
            </table>
          </td>            
    </tr>
</table>
</ssl:form>

<table class="defaultTableContentHidden" cellpadding="0" cellspacing="0">
	<tr>
		<td><input type="button" class="button" id="backButton" value="<bean:message key="global.back"/>"></td>
	</tr>
</table>

<table class="defaultTableContent" cellspacing="0" cellpadding="0">
    <tr>
        <td class="tdHeaderTable"><bean:message key="global.searchResults"/></td>
        <cyclos:help page="advertisements#imported_ad_details_result"/>
    </tr>
    <tr>
        <td colspan="2" align="left" class="tdContentTableLists">
			<table class="defaultTable">
				<tr>
					<td align="center" width="10%" class="tdHeaderContents"><bean:message key="adImport.lineNumber"/></td>
					<td class="tdHeaderContents"><bean:message key="ad.owner"/></td>
					<td class="tdHeaderContents"><bean:message key="ad.category"/></td>
					<td class="tdHeaderContents"><bean:message key="ad.price"/></td>
					<c:if test="${cyclos:name(query.status) != 'SUCCESS'}">
						<td class="tdHeaderContents"><bean:message key="adImport.status"/></td>
					</c:if>
				</tr>
				<c:set var="memberProperty" value="${localSettings.memberResultDisplay.property}"/>
				<c:forEach var="importedAd" items="${importedAds}">
					<tr class="<t:toggle>ClassColor1|ClassColor2</t:toggle>">
						<td align="center">${importedAd.lineNumber}</td>
						<td align="center">${importedAd.owner[memberProperty]}</td>
						<td>${empty importedAd.existingCategory ? importedAd.importedCategory.fullName : importedAd.existingCategory.fullName}</td>
						<td><cyclos:format number="${importedAd.price}" unitsPattern="${adImport.currency.pattern}" /></td>
						<c:if test="${cyclos:name(query.status) != 'SUCCESS'}">
							<td><bean:message key="adImport.status.${importedAd.status}" arg0="${importedAd.errorArgument1}" arg1="${importedAd.errorArgument2}"/></td>
						</c:if>
					</tr>
				</c:forEach>
			</table>
		</td>
	</tr>
</table>

<table class="defaultTableContentHidden" cellpadding="0" cellspacing="0">
	<tr>
		<td align="right"><cyclos:pagination items="${importedAds}"/></td>
	</tr>
</table>		

web/pages/productsServices/imports/importedAdsSummary.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://jakarta.apache.org/struts/tags/struts-bean" prefix="bean" %>
<%@ taglib uri="http://jakarta.apache.org/struts/tags/struts-html" prefix="html" %>
<%@ taglib uri="http://sslext.sf.net/tags/sslext" prefix="ssl" %>
<%@ taglib uri="http://devel.cyclos.org/tlibs/cyclos-core" prefix="cyclos" %>
<%@ taglib uri="http://www.servletsuite.com/servlets/toggletag" prefix="t" %> 

<cyclos:script src="/pages/productsServices/imports/importedAdsSummary.js" />

<ssl:form method="post" action="${formAction}">
<html:hidden property="importId" />

<table class="defaultTableContent" cellspacing="0" cellpadding="0">
    <tr>
        <td class="tdHeaderTable"><bean:message key="adImport.title.summary"/></td>
        <cyclos:help page="advertisements#imported_ads_summary"/>
    </tr>
    <tr>
        <td colspan="2" align="left" class="tdContentTableForms">
            <table class="defaultTable">
            	<c:if test="${empty singleCurrency}">
	                <tr>
	                    <td class="headerLabel" width="50%"><bean:message key="adImport.currency"/></td>
	                    <td class="headerField">${singleCurrency.name}</td>
	                </tr>
            	</c:if>
                <tr>
                    <td class="headerLabel" width="50%"><bean:message key="adImport.totalAds"/></td>
                    <td class="headerField"><a id="totalLink" class="default">${summary.total}</a></td>
                </tr>
                <tr>
                    <td class="headerLabel"><bean:message key="adImport.successfulAds"/></td>
                    <td class="headerField"><a id="successLink" class="default">${summary.total - summary.errors}</a></td>
                </tr>
                <tr>
                    <td class="headerLabel"><bean:message key="adImport.adsWithErrors"/></td>
                    <td class="headerField"><a id="errorLink" class="default">${summary.errors}</a></td>
                </tr>
                <tr>
                    <td class="headerLabel"><bean:message key="adImport.newCategories"/></td>
                    <td class="headerField"><a id="newCategoriesLink" class="default">${summary.newCategories}</a></td>
                </tr>
                <tr>
					<td><input type="button" id="backButton" class="button" value="<bean:message key="global.back"/>" ></td>
					<c:if test="${(summary.total - summary.errors) > 0}">
						<td align="right"><input type="submit" id="confirmButton" class="button" value="<bean:message key="adImport.confirm"/>" ></td>
					</c:if>
	            </tr>
             </table>
        </td>
    </tr>
</table>
</ssl:form>