src/nl/strohalm/cyclos/entities/Entity.java
/*
    This file is part of Cyclos (www.cyclos.org).
    A project of the Social Trade Organisation (www.socialtrade.org).

    Cyclos is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    Cyclos is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Cyclos; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

 */
package nl.strohalm.cyclos.entities;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;

import nl.strohalm.cyclos.entities.settings.LocalSettings;
import nl.strohalm.cyclos.utils.EntityHelper;
import nl.strohalm.cyclos.utils.EntityVO;

import org.springframework.beans.BeanWrapperImpl;

/**
 * Common class for all domain objects
 * @author luis
 */
public abstract class Entity implements Serializable, Cloneable {

    private static final long serialVersionUID = -7165508156631393668L;
    private Long              id;

    /**
     * Clones this entity
     */
    @Override
    public Object clone() {
        try {
            return super.clone();
        } catch (final CloneNotSupportedException e) {
            // Will NEVER happen, since entity is cloneable
            return null;
        }
    }

    @Override
    public boolean equals(final Object obj) {
        if (!(obj instanceof Entity)) {
            return false;
        }
        final Long id = getId();
        final Class<? extends Entity> thisRealClass = EntityHelper.getRealClass(this);
        final Class<? extends Entity> otherRealClass = EntityHelper.getRealClass((Entity) obj);
        if (id != null && (thisRealClass.isAssignableFrom(otherRealClass) || otherRealClass.isAssignableFrom(thisRealClass))) {
            final Entity other = (Entity) obj;
            return id.equals(other.getId());
        }
        return false;
    }

    public Long getId() {
        return id;
    }

    /**
     * This method could be overridden by subclasses to return the entity's name<br>
     * By default it invoke by reflection a getName() method, if not, returns id#simple_class_name
     */
    public String getName() {
        try {
            return new BeanWrapperImpl(this).getPropertyValue("name").toString();
        } catch (final Exception e) {
            return id + "#" + getClass().getSimpleName();
        }
    }

    /**
     * Returns a map containing placeholder values for messages
     */
    public Map<String, Object> getVariableValues(final LocalSettings localSettings) {
        final Map<String, Object> values = new HashMap<String, Object>();
        appendVariableValues(values, localSettings);
        return values;
    }

    @Override
    public int hashCode() {
        final Long id = getId();
        return id == null ? super.hashCode() : id.hashCode();
    }

    /**
     * Return if this entity was already persisted - It has a valid identifier
     */
    public boolean isPersistent() {
        return id != null;
    }

    /**
     * Return if this entity was not yet persisted - It has a null identifier
     */
    public boolean isTransient() {
        return id == null;
    }

    /**
     * @return a read-only view of this entity
     * @see #getName()
     */
    public EntityVO readOnlyView() {
        return new EntityVO(getId(), getName());
    }

    /**
     * Set the id
     * @throws IllegalStateException When the entity already had an identifier
     */
    public void setId(final Long id) throws IllegalStateException {
        this.id = id;
    }

    @Override
    public abstract String toString();

    /**
     * Should be overriden by subclasses to append variable values on the given map
     */
    protected void appendVariableValues(final Map<String, Object> variables, final LocalSettings localSettings) {
    }

    @SuppressWarnings("unchecked")
    protected Object writeReplace() {
        if (this instanceof EntityReference) {
            return new EntityReference.Resolver((Class<? extends Entity>) getClass().getSuperclass(), getId());
        }
        return this;
    }
}

src/nl/strohalm/cyclos/entities/customization/binaryfiles/BinaryFile.java
/*
    This file is part of Cyclos (www.cyclos.org).
    A project of the Social Trade Organisation (www.socialtrade.org).

    Cyclos is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    Cyclos is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Cyclos; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

 */
package nl.strohalm.cyclos.entities.customization.binaryfiles;

import java.sql.Blob;
import java.util.Calendar;

import nl.strohalm.cyclos.entities.Entity;

/**
 * Stores a binary file
 * @author Jefferson Magno
 */
public class BinaryFile extends Entity {

    private static final long serialVersionUID = -5332038464288668149L;
    private String            contentType;
    private String            name;
    private Integer           size;
    private Calendar          lastModified;
    private Blob              contents;

    public Blob getContents() {
        return contents;
    }

    public String getContentType() {
        return contentType;
    }

    public Calendar getLastModified() {
        return lastModified;
    }

    public String getName() {
        return name;
    }

    public Integer getSize() {
        return size;
    }

    public void setContents(final Blob contents) {
        this.contents = contents;
    }

    public void setContentType(final String contentType) {
        this.contentType = contentType;
    }

    public void setLastModified(final Calendar lastModified) {
        this.lastModified = lastModified;
    }

    public void setName(final String name) {
        this.name = name;
    }

    public void setSize(final Integer size) {
        this.size = size;
    }

    @Override
    public String toString() {
        return getId() == null ? "" : getId().toString();
    }

}

src/nl/strohalm/cyclos/entities/customization/documents/Document.java
/*
    This file is part of Cyclos (www.cyclos.org).
    A project of the Social Trade Organisation (www.socialtrade.org).

    Cyclos is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    Cyclos is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Cyclos; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

 */
package nl.strohalm.cyclos.entities.customization.documents;

import java.util.ArrayList;
import java.util.Collection;

import nl.strohalm.cyclos.entities.Entity;
import nl.strohalm.cyclos.entities.Relationship;
import nl.strohalm.cyclos.entities.groups.BrokerGroup;
import nl.strohalm.cyclos.entities.groups.SystemGroup;
import nl.strohalm.cyclos.utils.StringValuedEnum;

/**
 * Is a customized document, it can be static or dynamic
 * @author luis
 * @author Jefferson Magno
 */
public abstract class Document extends Entity {

    public static enum Nature implements StringValuedEnum {
        DYNAMIC("D"), STATIC("S"), MEMBER("M");

        private String value;

        private Nature(final String value) {
            this.value = value;
        }

        public Class<? extends Document> getType() {
            return this == DYNAMIC ? DynamicDocument.class : (this == STATIC ? StaticDocument.class : MemberDocument.class);
        }

        @Override
        public String getValue() {
            return value;
        }
    }

    public static enum Relationships implements Relationship {
        GROUPS("groups"), BROKER_GROUPS("brokerGroups");
        private final String name;

        private Relationships(final String name) {
            this.name = name;
        }

        @Override
        public String getName() {
            return name;
        }
    }

    private static final long       serialVersionUID = -2006379424571494005L;
    private String                  name;
    private String                  description;
    private Collection<SystemGroup> groups;
    private Collection<BrokerGroup> brokerGroups;

    public void addGroup(final SystemGroup g) {
        if (groups == null) {
            groups = new ArrayList<SystemGroup>();
        }

        groups.add(g);
    }

    public Collection<BrokerGroup> getBrokerGroups() {
        return brokerGroups;
    }

    public String getDescription() {
        return description;
    }

    public Collection<SystemGroup> getGroups() {
        return groups;
    }

    public String getName() {
        return name;
    }

    public abstract Nature getNature();

    public void setBrokerGroups(final Collection<BrokerGroup> brokerGroups) {
        this.brokerGroups = brokerGroups;
    }

    public void setDescription(final String description) {
        this.description = description;
    }

    public void setGroups(final Collection<SystemGroup> groups) {
        this.groups = groups;
    }

    public void setName(final String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return getId() + " - " + name;
    }

}

src/nl/strohalm/cyclos/entities/customization/documents/DocumentPage.java
/*
    This file is part of Cyclos (www.cyclos.org).
    A project of the Social Trade Organisation (www.socialtrade.org).

    Cyclos is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    Cyclos is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Cyclos; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

 */
package nl.strohalm.cyclos.entities.customization.documents;

import nl.strohalm.cyclos.entities.Relationship;
import nl.strohalm.cyclos.entities.customization.files.File;

/**
 * A document page, may be a form for entering parameters, or the document display page itself
 * @author luis
 */
public class DocumentPage extends File {

    public static enum Relationships implements Relationship {
        DOCUMENT("document");
        private final String name;

        private Relationships(final String name) {
            this.name = name;
        }

        public String getName() {
            return name;
        }
    }

    private static final long serialVersionUID = -8540979747354200297L;

    private Document          document;

    public Document getDocument() {
        return document;
    }

    public void setDocument(final Document document) {
        this.document = document;
    }
}

src/nl/strohalm/cyclos/entities/customization/documents/DocumentQuery.java
/*
    This file is part of Cyclos (www.cyclos.org).
    A project of the Social Trade Organisation (www.socialtrade.org).

    Cyclos is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    Cyclos is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Cyclos; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

 */
package nl.strohalm.cyclos.entities.customization.documents;

import java.util.Collection;

import nl.strohalm.cyclos.entities.groups.Group;
import nl.strohalm.cyclos.entities.members.Element;
import nl.strohalm.cyclos.entities.members.Member;
import nl.strohalm.cyclos.utils.query.QueryParameters;

/**
 * Query parameters for documents
 * @author luis
 * @author Jefferson Magno
 */
public class DocumentQuery extends QueryParameters {

    private static final long           serialVersionUID             = 3786759993229052921L;
    private boolean                     brokerCanViewMemberDocuments = false;
    private Member                      member;
    private Collection<Document.Nature> natures;
    private Element                     viewer;
    private Long                        id;
    private Collection<Group>           visibleGroups;

    public Long getId() {
        return id;
    }

    public Member getMember() {
        return member;
    }

    public Collection<Document.Nature> getNatures() {
        return natures;
    }

    public Element getViewer() {
        return viewer;
    }

    public Collection<Group> getVisibleGroups() {
        return visibleGroups;
    }

    public boolean isBrokerCanViewMemberDocuments() {
        return brokerCanViewMemberDocuments;
    }

    public void setBrokerCanViewMemberDocuments(final boolean brokerCanViewMemberDocuments) {
        this.brokerCanViewMemberDocuments = brokerCanViewMemberDocuments;
    }

    public void setId(final Long id) {
        this.id = id;
    }

    public void setMember(final Member member) {
        this.member = member;
    }

    public void setNatures(final Collection<Document.Nature> natures) {
        this.natures = natures;
    }

    public void setViewer(final Element viewer) {
        this.viewer = viewer;
    }

    public void setVisibleGroups(final Collection<Group> visibleGroups) {
        this.visibleGroups = visibleGroups;
    }
}

src/nl/strohalm/cyclos/entities/customization/documents/DynamicDocument.java
/*
    This file is part of Cyclos (www.cyclos.org).
    A project of the Social Trade Organisation (www.socialtrade.org).

    Cyclos is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    Cyclos is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Cyclos; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

 */
package nl.strohalm.cyclos.entities.customization.documents;

import nl.strohalm.cyclos.entities.Relationship;

import org.apache.commons.lang.StringUtils;

/**
 * Is a customized document, that will have custom pages for (optionally) displaying a form with parameters and show a document
 * @author luis
 */
public class DynamicDocument extends Document {

    public static enum Relationships implements Relationship {
        FORM_PAGE("formPage"), DOCUMENT_PAGE("documentPage");
        private final String name;

        private Relationships(final String name) {
            this.name = name;
        }

        public String getName() {
            return name;
        }
    }

    private static final long serialVersionUID = -3105332690172908757L;
    private DocumentPage      formPage;
    private DocumentPage      documentPage;

    public DocumentPage getDocumentPage() {
        return documentPage;
    }

    public DocumentPage getFormPage() {
        return formPage;
    }

    @Override
    public Nature getNature() {
        return Nature.DYNAMIC;
    }

    public boolean isHasFormPage() {
        return formPage != null && StringUtils.isNotEmpty(formPage.getContents());
    }

    public void setDocumentPage(final DocumentPage documentPage) {
        this.documentPage = documentPage;
    }

    public void setFormPage(final DocumentPage formPage) {
        this.formPage = formPage;
    }

}

web/pages/customization/files/editCustomizedFile.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://jakarta.apache.org/struts/tags/struts-html" prefix="html" %>
<%@ taglib uri="http://jakarta.apache.org/struts/tags/struts-bean" prefix="bean" %>
<%@ taglib uri="http://sslext.sf.net/tags/sslext" prefix="ssl" %>
<%@ taglib uri="http://devel.cyclos.org/tlibs/cyclos-core" prefix="cyclos" %>
<cyclos:script src="/pages/customization/files/editCustomizedFile.js" />

<script>
	var type = "${file.type}";
	var isTransient = ${file['transient']};
	var chooseLabel = "<cyclos:escapeJS><bean:message key='global.choose'/></cyclos:escapeJS>";
</script>

<c:choose>
	<c:when test="${type == 'STATIC_FILE'}">
		<c:set var="titleKey" value="customizedFile.title.customize.static"/>
		<c:set var="helpPage" value="content_management#edit_customized_file"/>
	</c:when>
	<c:when test="${type == 'HELP'}">
		<c:set var="titleKey" value="customizedFile.title.customize.help"/>
		<c:set var="helpPage" value="content_management#edit_customized_file"/>
	</c:when>
	<c:when test="${type == 'STYLE'}">
		<c:set var="titleKey" value="customizedFile.title.customize.css"/>
		<c:set var="helpPage" value="content_management#edit_customized_file"/>
	</c:when>
	<c:when test="${type == 'APPLICATION_PAGE'}">
		<c:set var="titleKey" value="customizedFile.title.customize.page"/>
	</c:when>
</c:choose>
<c:choose>
	<c:when test="${file['transient']}">
		<c:set var="helpPage" value="content_management#edit_new_customized_file"/>
	</c:when>
	<c:otherwise>
		<c:set var="helpPage" value="content_management#edit_customized_file"/>
	</c:otherwise>
</c:choose>

<ssl:form method="post" action="${formAction}" >
<html:hidden property="file(id)" />
<html:hidden property="file(type)"/>
<table class="defaultTableContent" cellspacing="0" cellpadding="0">
    <tr>
        <td class="tdHeaderTable"><bean:message key="${titleKey}"/></td>
        <cyclos:help page="${helpPage}"/>
    </tr>
    <tr>
        <td colspan="2" align="left" class="tdContentTableForms">
			<table class="defaultTable">
				<c:if test="${not empty file.newContents}">
					<tr>
						<td align="center" colspan="2"><br class='small'/><cyclos:escapeHTML brOnly="true"><bean:message key="customizedFile.newContentsNotification"/></cyclos:escapeHTML><br class='small'/><br class='small'/></td>
					</tr>
				</c:if>
				<c:choose>
					<c:when test="${type == 'APPLICATION_PAGE'}">
						
						<c:choose><c:when test="${file['transient']}">
							<tr>
								<td class="label" width="20%"><bean:message key="customizedFile.path"/></td>
								<td><input type="text" name="filePath" value="${file.relativePath != null ? file.relativePath : "/" }" class="full InputBoxDisabled"/></td>
							</tr>
							<tr>
								<td class="label" width="20%"><bean:message key="customizedFile.select.name"/></td>
								<td>	
									<html:hidden property="file(name)"/>
									<select id="contentSelect" name="contentSelect">
										<option value=""><bean:message key="global.choose"/></option>
									</select>
									<span id="upLevelLink">&nbsp;<a class="default" href="javascript:upLevel()"><bean:message key="global.up"/></a></span>
								</td>
							</tr>
						</c:when><c:otherwise>
							<tr>
								<td class="label" width="20%"><bean:message key="customizedFile.path"/></td>
								<td>	
									<html:text property="file(name)" styleClass="full InputBoxDisabled"/>
								</td>
							</tr>
						</c:otherwise></c:choose>
					</c:when>
					<c:otherwise>
						<c:choose><c:when test="${file['transient']}">
							<tr>
								<td class="label" width="20%"><bean:message key="customizedFile.select.name"/></td>
								<td>
									<html:select styleId="fileSelect" property="file(name)">
										<c:forEach var="current" items="${filesNotYetCustomized}">
											<html:option value="${current}">${current}</html:option>
										</c:forEach>
									</html:select>
								</td>
							</tr>
						</c:when><c:otherwise>
							<tr>
								<td class="label" width="20%"><bean:message key="customizedFile.name"/></td>
								<td>
									<html:hidden property="file(name)"/>
									<input id="fileName" value="${file.name}" class="full InputBoxDisabled" readonly/>
								</td>
							</tr>
						</c:otherwise></c:choose>
					</c:otherwise>
				</c:choose>
				<tr>
					<td class="label" valign="top"><bean:message key="customizedFile.contents"/></td>
					<td><html:textarea styleId="contents" property="file(contents)" value="${file.contents}" rows="20" styleClass="full InputBoxDisabled" readonly="true"/></td>
				</tr>
				<c:if test="${not empty file.newContents}">
					<tr>
						<td class="label" valign="top"><bean:message key="customizedFile.newContents"/></td>
						<td><html:textarea styleId="contents" property="file(newContents)" rows="20" styleClass="full InputBoxDisabled" readonly="true"/></td>
					</tr>
				</c:if>
				<c:if test="${file.persistent and not emptyfile.originalContents}">
				<tr id="showOriginalContents">
					<td class="label" valign="top"><bean:message key="customizedFile.originalContents"/></td>
					<td>
						&nbsp;<a class="default" href="javascript:showOriginalContents(true)"><bean:message key="global.show"/></a>
					</td>
				</tr>
				
				<tr id="originalContents" style="display:none">
					<td class="label" valign="top"><bean:message key="customizedFile.originalContents"/></td>
					<td>
						&nbsp;<a class="default" href="javascript:showOriginalContents(false)"><bean:message key="global.hide"/></a>
						<html:textarea styleId="contents" property="file(originalContents)" rows="20" styleClass="full InputBoxDisabled" readonly="true"/>
					</td>
				</tr>
				</c:if>
				<tr>
					<td colspan="2" align="right">
						<c:if test="${file.conflict}">
							<input type="checkbox" name="resolveConflicts" id="resolveCheck" class="checkbox" disabled="disabled"/> <bean:message key="customizedFile.resolveConflict"/> &nbsp;
						</c:if>
			       		<input type="button" id="modifyButton" value="<bean:message key="global.change"/>" class="button">
			       		&nbsp;
						<input type="submit" id="saveButton" value="<bean:message key="global.submit"/>" class="ButtonDisabled" disabled>
								
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<table class="defaultTableContentHidden">
	<tr>
		<td align="left"><input id="backButton" type="button" class="button" value="<bean:message key="global.back"/>"></td>
	</tr>
</table>
</ssl:form>

web/pages/customization/files/listCustomizedFiles.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://jakarta.apache.org/struts/tags/struts-html" prefix="html" %>
<%@ taglib uri="http://www.servletsuite.com/servlets/toggletag" prefix="t" %> 
<%@ taglib uri="http://sslext.sf.net/tags/sslext" prefix="ssl" %>
<%@ taglib uri="http://jakarta.apache.org/struts/tags/struts-bean" prefix="bean" %>
<%@ taglib uri="http://devel.cyclos.org/tlibs/cyclos-core" prefix="cyclos" %>

<cyclos:script src="/pages/customization/files/listCustomizedFiles.js" />
<script>
	var removeConfirmationMessage = "<cyclos:escapeJS><bean:message key="customizedFile.removeConfirmation"/></cyclos:escapeJS>";
	var type = "${type}";
</script>

<c:choose>
	<c:when test="${type == 'STATIC_FILE'}">
		<c:set var="titleKey" value="customizedFile.title.search.static"/>
		<c:set var="helpPage" value="content_management#customized_files"/>
	</c:when>
	<c:when test="${type == 'HELP'}">
		<c:set var="titleKey" value="customizedFile.title.search.help"/>
		<c:set var="helpPage" value="content_management#customized_files"/>
	</c:when>
	<c:when test="${type == 'STYLE'}">
		<c:set var="titleKey" value="customizedFile.title.search.css"/>
		<c:set var="helpPage" value="content_management#customized_files"/>
	</c:when>
	<c:when test="${type == 'APPLICATION_PAGE'}">
		<c:set var="titleKey" value="customizedFile.title.applicationPage"/>
		<c:set var="helpPage" value="content_management#customized_files"/>
	</c:when>
	
</c:choose>

<table class="defaultTableContent" cellspacing="0" cellpadding="0">
    <tr>
        <td class="tdHeaderTable"><bean:message key="${titleKey}"/></td>
        <cyclos:help page="${helpPage}"/>
    </tr>
    <tr>
        <td colspan="2" align="left" class="tdContentTableLists">
            <table class="defaultTable">
                <tr>
                	<td class="tdHeaderContents"><bean:message key="customizedFile.name"/></td>
                    <td class="tdHeaderContents" width="15%">&nbsp;</td>
                </tr>
                <c:forEach var="file" items="${files}">
	                <c:set var="fileNameClass" value=""/>
                	<c:if test="${file.conflict}">
                		<c:set var="fileNameClass" value="class='conflict'"/>
                	</c:if>
	                <tr class="<t:toggle>ClassColor1|ClassColor2</t:toggle>">
	                	<td><span ${fileNameClass}>${file.name}</span></td>
	                    <td align="center" nowrap="nowrap">
	                    	<c:if test="${type != 'STYLE' && type != 'APPLICATION_PAGE'}">
	                    		<img class="preview" src="<c:url value="/pages/images/preview.gif"/>" fileName="<cyclos:escapeHTML>${file.name}</cyclos:escapeHTML>" border="0">
	                    	</c:if>
	                    	<c:if test="${cyclos:granted(AdminSystemPermission.CUSTOMIZED_FILES_MANAGE)}">
		                    	<img class="edit" src="<c:url value="/pages/images/edit.gif"/>" fileId="${file.id}" border="0">
		                    	<img class="remove" src="<c:url value="/pages/images/delete.gif"/>" fileId="${file.id}" border="0">
		                    </c:if>
	                    </td>
	                </tr>
                </c:forEach>
			</table>
		</td>
	</tr>
</table>

<c:if test="${cyclos:granted(AdminSystemPermission.CUSTOMIZED_FILES_MANAGE)}">
	<table class="defaultTableContentHidden">
		<tr>
			<td align="right">
				<span class="label"><bean:message key="customizedFile.action.customizeNew"/></span>
				<input type="button" class="button" id="newButton" value="<bean:message key="global.submit"/>">
			</td>
		</tr>
	</table>
</c:if>
		

web/pages/customization/files/showCustomizedFile.jsp
<%@ taglib uri="http://jakarta.apache.org/struts/tags/struts-bean" prefix="bean" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://devel.cyclos.org/tlibs/cyclos-core" prefix="cyclos" %>

<c:set var="type" value="${param.type}"/>
<c:set var="fileName" value="${param.fileName}"/>
<c:set var="groupId" value="${param.groupId}"/>
<c:set var="groupFilterId" value="${param.groupFilterId}"/>
<c:choose>
	<c:when test="${type == 'STATIC_FILE'}">
		<c:set var="type" value="static"/>
	</c:when>
	<c:when test="${type == 'HELP'}">
		<c:set var="type" value="help"/>
	</c:when>
</c:choose>
<table class="defaultTable">
	<tr>
		<td align="center" valign="top">

			<table class="defaultTableContent" cellspacing="0" cellpadding="0">
				<tr>
					<td class="tdHeaderTable" width="50%" nowrap="nowrap" height="16px"><bean:message key="customizedFile.title.preview" arg0="${fileName}"/></td>
					<td class="tdHelpIcon">&nbsp;</td>
				</tr>
				<tr>
			 		<td colspan="2">
			 			<cyclos:includeCustomizedFile type="${type}" name="${fileName}" groupId="${groupId}" groupFilterId="${groupFilterId}"/>
					</td>
				</tr>
			</table>
			
			<input type="button" onclick="window.close();" class="button" value="<bean:message key="global.close"/>">
		</td>
	</tr>
</table>